name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.4.2+14

environment:
  sdk: ^3.4.3
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.38
  audio_service: 0.18.13
  audio_session: 0.1.19
  shared_preferences: 2.2.3
  flex_color_scheme: 7.3.1
  provider: 6.1.2
  scrollable_positioned_list: 0.3.8
  flutter_html: 3.0.0-beta.2
  flutter_html_table: 3.0.0-beta.2
  super_tooltip: 2.0.7
  url_launcher: 6.3.0
  package_info_plus: 8.0.0
  intl: 0.19.0
  collection: 1.18.0
  path: 1.9.0

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
