name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.4.0+12

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.28
  audio_service: 0.18.7
  audio_session: 0.1.10
  shared_preferences: 2.0.15
  flex_color_scheme: 5.1.0
  provider: 6.0.3
  scrollable_positioned_list: 0.3.2
  flutter_html: 2.2.1
  super_tooltip: 1.0.1
  url_launcher: 6.1.5
  package_info_plus: 1.4.3
  intl: 0.17.0
  collection: 1.16.0
  path: 1.8.1

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
