name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.4.0+12

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.3.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.30
  audio_service: 0.18.7
  audio_session: 0.1.10
  shared_preferences: 2.0.15
  flex_color_scheme: 6.0.1
  provider: 6.0.4
  scrollable_positioned_list: 0.3.5
  flutter_html: 2.2.1
  super_tooltip: 1.0.1
  url_launcher: 6.1.6
  package_info_plus: 3.0.1
  intl: 0.17.0
  collection: 1.16.0
  path: 1.8.2

  wakelock: 0.6.2 # only to fix the build

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
