name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.3.2+10

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.18
  audio_service: 0.18.3
  audio_session: 0.1.6+1
  shared_preferences: 2.0.11
  flex_color_scheme: 4.1.1
  provider: 6.0.1
  scrollable_positioned_list: 0.2.3
  flutter_html: 2.2.1
  super_tooltip: 1.0.1
  url_launcher: 6.0.17
  package_info_plus: 1.3.0
  intl: 0.17.0
  collection: 1.15.0
  path: 1.8.0

dev_dependencies:
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
