name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.5.2+17

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.10.2
  audio_service: 0.18.18
  audio_session: 0.2.1
  shared_preferences: 2.5.3
  flex_color_scheme: 8.2.0
  provider: 6.1.5
  scrollable_positioned_list: 0.3.8
  super_tooltip: 2.0.9
  collection: any
  path: any

  help_page:
    git:
      url: https://github.com/z80maniac/flutter_help_page.git
      ref: b78390dd7ffe5d1d48e09c87249b334cf58e5174

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
