name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.4.1+13

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.34
  audio_service: 0.18.10
  audio_session: 0.1.16
  shared_preferences: 2.1.2
  flex_color_scheme: 7.1.2
  provider: 6.0.5
  scrollable_positioned_list: 0.3.8
  flutter_html: 3.0.0-beta.2
  flutter_html_table: 3.0.0-beta.2
  super_tooltip: 1.0.1
  url_launcher: 6.1.11
  package_info_plus: 4.0.2
  intl: 0.18.0
  collection: 1.17.1
  path: 1.8.3

dev_dependencies:
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
