name: sonuspresto
description: >
  A bare-bones music player.
  Intended to utilize a filesystem to browse your music instead of automatically grouping by artist, album or genre.
  Focused on gesture controls.
  Supports CUE sheets, M3U playlists and Internet radio.

version: 0.5.0+15

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.42
  audio_service: 0.18.16
  audio_session: 0.1.23
  shared_preferences: 2.3.4
  flex_color_scheme: 8.0.2
  provider: 6.1.2
  scrollable_positioned_list: 0.3.8
  super_tooltip: 2.0.9
  collection: 1.19.0
  path: 1.9.0

  help_page:
    git:
      url: https://github.com/z80maniac/flutter_help_page.git
      ref: 3464f5acadba56d49f7e38b5684acffdf19b2fad

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  generate: true

publish_to: "none"
