default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play"
  lane :upload_play do
    upload_to_play_store(aab: 'android/build/app/outputs/bundle/release/app-release.aab')
  end
end
